<?php

/*
	Do not edit this file manually. This copy of global file is overwritten
	by extensions editor.
*/

$installed_extensions = array (
  1 => 
  array (
    'package' => 'sales_partial_payment',
    'name' => 'sales_partial_payment',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/sales_partial_payment',
    'active' => 1,
  ),
  2 => 
  array (
    'package' => 'KvcodesSMSGateway',
    'name' => 'KvcodesSMSGateway',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/KvcodesSMSGateway',
    'active' => 1,
  ),
  6 => 
  array (
    'name' => 'FrontHrm',
    'package' => 'fronthrm',
    'version' => '2.4.0-1',
    'type' => 'extension',
    'active' => 1,
    'path' => 'modules/FrontHrm',
  ),
  7 => 
  array (
    'package' => 'FrontHrm',
    'name' => 'FrontHrm',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/FrontHrm',
    'active' => 1,
  ),
);
